const journalTranslations = {
  'Автоматика и телемеханика': 'Automation and Remote Control',
  'Азия и Африка сегодня': 'Asia and Africa Today',
  'Акустический жунал': 'Acoustical Physics',
  'Астрономический вестник': 'Solar System Research',
  'Астрономический вестник. ИСС': 'Solar System Research',
  'Астрономический вестник. Исследования солнечной системы': 'Solar System Research',
  'Астрономический журнал': 'Astronomy Reports',
  'Биологические мембраны': 'Membrane and Cell Biology',
  'Биология внутренних вод': 'Inland Water Biology',
  'Биология моря': 'Russian Journal of Marine Biology',
  'Биоорганическая химия': 'Russian Journal of Bioorganic Chemistry',
  'Биофизика': 'Biophysics',
  'Биохимия': 'Biochemistry (Moscow)',
  'Вестник Российской академии наук': 'Herald of the Russian Academy of Sciences',
  'Вестник РАН': 'Herald of the Russian Academy of Sciences',
  'Водные ресурсы': 'Water Resources',
  'Вопросы истории естествознания и техники': 'Studies in the History of Science and Technology',
  'Вопросы ихтиологии': 'Journal of Ichthyology',
  'Вулканология и сейсмология': 'Journal of Volcanology and Seismology',
  'Высокомолекулярные соединения. Серия А': 'Polymer Science, Series A',
  'Высокомолекулярные соединения. Серия Б': 'Polymer Science, Series B',
  'Высокомолекулярные соединения. Серия С': 'Polymer Science, Series C',
  'Генетика': 'Russian Journal of Genetics',
  'Геология рудных месторождений': 'Geology of Ore Deposits',
  'Геомагнетизм и аэрономия': 'Geomagnetism and Aeronomy',
  'Геотектоника': 'Geotectonics',
  'Геохимия': 'Geochemistry International',
  'Геоэкология. Инженерная геология. Гидрогеология. Геокриология': 'Environmental Geoscience',
  'Государство и право': 'Государство и право',
  'Дефектоскопия': 'Russian Journal of Nondestructive Testing',
  'Дифференциальные уравнения': 'Differential Equations',
  'ДРАН. Математика, информатика, процессы управления': 'Doklady Mathematics',
  'ДРАН. Науки о жизни': 'Doklady Biological Sciences',
  'ДРАН. Науки о Земле': 'Doklady Earth Sciences',
  'ДРАН. Физика, технические науки': 'Doklady Physics',
  'Доклады РАН. Математика, информатика, процессы управления': 'Doklady Mathematics',
  'Доклады РАН. Науки о жизни': 'Doklady Biological Sciences',
  'Доклады Российской академии наук. Математика, информатика, процессы управления': 'Doklady Mathematics',
  'Доклады Российской академии наук. Науки о жизни': 'Doklady Biological Sciences',
  'Доклады Российской академии наук. Науки о Земле': 'Doklady Earth Sciences',
  'Доклады Российской академии наук. Физика, технические науки': 'Doklady Physics',
  'Доклады Российской академии наук. Химия, науки о материалах': 'Doklady Chemistry',
  'Журнал аналитической химии': 'Journal of Analytical Chemistry',
  'Журнал вычистлительной математики и математической физики': 'Computational Mathematics and Mathematical Physics',
  'Журнал неорганической химии': 'Журнал неорганической химии',
  'Журнал общей биологии': 'Journal of General Biology',
  'Журнал общей химии': 'Russian Journal of General Chemistry',
  'Журнал органической химии': 'Russian Journal of Organic Chemistry',
  'Журнал прикладной химии': 'Журнал прикладной химии',
  'Журнал физической химии': 'Russian Journal of Physical Chemistry',
  'Журнал эволюционной биохимии и физиологии': 'Journal of Evolutionary Biochemistry and Physiology',
  'Журнал экспериментальной и теоретической физики (ЖЭТФ)': 'Journal of Experimental and Theoretical Physics',
  'Журнал экспериментальной и теоретической физики': 'Journal of Experimental and Theoretical Physics',
  'ЖЭТФ': 'Journal of Experimental and Theoretical Physics',
  'Записки Российского минералогического общества': 'Zapiski of the Russian Mineralogical Society',
  'Записки российского минералогического общества': 'Zapiski of the Russian Mineralogical Society',
  'Зоологический журнал': 'Зоологический журнал',
  'Зоологический': 'Зоологический журнал',
  'Известия РАН. Механика жидкости и газа': 'Fluid Dynamics',
  'Известия РАН. Механика твёрдого тела': 'Mechanics of Solids',
  'Известия РАН. Серия биологическая': 'Biology Bulletin',
  'Известия РАН. Серия географическая': 'Bulletin of the RAS. Geography',
  'Известия РАН. Серия физическая': 'Bulletin of the Russian Academy of Sciences: Physics',
  'Известия РАН. Теория систем управления': 'Journal of Computer and System Sciences International',
  'Известия РАН. Физика атмосферы и океана': 'Izvestiya, Atmospheric and Oceanic Physics',
  'Изв.РАН. Механика жидкости и газа': 'Fluid Dynamics',
  'Изв.РАН. Механика твёрдого тела': 'Mechanics of Solids',
  'Изв.РАН. Серия биологическая': 'Biology Bulletin',
  'Изв.РАН. Серия географическая': 'Bulletin of the RAS. Geography',
  'Изв.РАН. Серия физическая': 'Bulletin of the Russian Academy of Sciences: Physics',
  'Изв.РАН. Теория систем управления': 'Journal of Computer and System Sciences International',
  'Изв.РАН. Физика атмосферы и океана': 'Izvestiya, Atmospheric and Oceanic Physics',
  'ИРАН. Механика жидкости и газа': 'Fluid Dynamics',
  'ИРАН. Механика твёрдого тела': 'Mechanics of Solids',
  'ИРАН. Серия биологическая': 'Biology Bulletin',
  'ИРАН. Серия географическая': 'Bulletin of the RAS. Geography',
  'ИРАН. Серия физическая': 'Bulletin of the Russian Academy of Sciences: Physics',
  'ИРАН. Теория систем управления': 'Journal of Computer and System Sciences International',
  'ИРАН. Физика атмосферы и океана': 'Izvestiya, Atmospheric and Oceanic Physics',
  'Известия РГО': 'Известия Русского географического общества',
  'Известия Русского географического общества': 'Известия Русского географического общества',
  'Исследование Земли из Космоса': 'Earth Research from Space',
  'Кинетика и катализ': 'Kinetics and Catalysis',
  'Коллоидный журнал': 'Colloid Journal',
  'Коллойдный журнал': 'Colloid Journal',
  'Координационная химия': 'Russian Journal of Coordination Chemistry',
  'Космические исследования': 'Cosmic Research',
  'Кристаллография': 'Crystallography Reports',
  'Лесоведение': 'Forest Science',
  'Литология и полезные ископаемые': 'Lithology and Mineral Resources',
  'Мембраны и мембранные технологии': 'Мембраны и мембранные технологии',
  'Металлы': 'Russian Metallurgy',
  'Микробиология': 'Microbiology',
  'Микроэлектроника': 'Russian Microelectronics',
  'Молекулярная биология': 'Molecular Biology',
  'Нейрохимия': 'Neurochemical Journal',
  'Неорганические материалы': 'Inorganic Materials',
  'Нефтехимия': 'Petroleum Chemistry',
  'Новая и новейшая история': 'Modern and Contemporary History',
  'Океанология': 'Oceanology',
  'Онтогенез': 'Russian Journal of Developmental Biology',
  'Палеонтологический журнал': 'Paleontological Journal',
  'Паразитология': 'Parasitology',
  'Петрология': 'Petrology',
  'Письма в Астрономический журнал': 'Astronomy Letters',
  'Поверхность': 'Journal of Surface Investigation. X-Ray, Synchrotron and Neutron Techniques',
  'Письма в ЖЭТФ': 'JETP Letters (Journal of Experimental and Theoretical Physics Letters)',
  'Письма в Журнал экспериментальной и теоретической физики': 'JETP Letters (Journal of Experimental and Theoretical Physics Letters)',
  'Поверхность. Рентгеновские, синхротронные и нейтронные исследования': 'Journal of Surface Investigation. X-Ray, Synchrotron and Neutron Techniques',
  'Почвоведение': 'Eurasian Soil Science',
  'Приборы и техника эксперимента': 'Instruments and Experimental Techniques',
  'Прикладная биохимия и микробиология': 'Applied Biochemistry and Microbiology',
  'Прикладная математика и механика': 'Journal of Applied Mathematics and Mechanics',
  'Проблемы Дальнего Востока': 'Far Eastern Studies',
  'Проблемы машиностроения и надежности машин': 'Journal of Machinery Manufacture and Reliability',
  'Проблемы передачи информации': 'Problems of Information Transmission',
  'Программирование': 'Programming and Computer Software',
  'Радиотехника и электроника': 'Journal of Communications Technology and Electronics',
  'Радиохимия': 'Radiochemistry',
  'Расплавы': 'Расплавы',
  'Российская археология': 'Russian Archaeology',
  'Российская история': 'Russian History', 
  'Стратиграфия': 'Stratigraphy and Geological Correlation',
  'Стратиграфия. Геологическая корреляция': 'Stratigraphy and Geological Correlation',
  'Теоретические основы химической технологии': 'Theoretical Foundations of Chemical Engineering',
  'Теплофизика высоких температур': 'High Temperature',
  'Физика Земли': 'Izvestiya, Physics of the Solid Earth',
  'Физика и химия стекла': 'Glass Physics and Chemistry',
  'Физика металлов и металловедение': 'Physics of Metals and Metallography',
  'Физика плазмы': 'Plasma Physics Reports',
  'Физикохимия поверхности и защита материалов': 'Protection of Metals and Physical Chemistry of Surfaces',
  'Физиология растений': 'Russian Journal of Plant Physiology',
  'Физиология человека': 'Human Physiology',
  'Химическая физика': 'Advances in Chemical Physics',
  'Химия высоких энергий': 'High Energy Chemistry',
  'Химия твердого топлива': 'Solid Fuel Chemistry',
  'Цитология': 'Cell and Tissue Biology',
  'Человек': 'The Human Being',
  'Экология': 'Russian Journal of Ecology',
  'Электрохимия': 'Russian Journal of Electrochemistry',
  'Энтомологическое обозрение': 'Entomological Review',
  'Ядерная физика': 'Physics of Atomic Nuclei'
}

export function findJournalTranslation(russianName) {
  if (!russianName) return null;
  
  // Normalize the input string
  const normalizedName = russianName.trim()
    .normalize('NFKC'); // Use NFKC normalization for better compatibility
    
  // Normalize all keys for comparison
  const normalizedTranslations = Object.fromEntries(
    Object.entries(journalTranslations).map(([key, value]) => [
      key.normalize('NFKC'),
      value
    ])
  );
  
  return normalizedTranslations[normalizedName] || null;
}
